blank_issues_enabled: false
contact_links:
  - name: Questions & discussions
    url: https://github.com/dushaobindoudou/dsh-refine/discussions
    about: Ask questions and discuss usage scenarios in GitHub Discussions.
